language: php

php:
  - 5.2
  - 5.3

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - wget https://github.com/cakephp/cakephp/tarball/1.3.15 -O cake.tar.gz
  - tar xf cake.tar.gz
  - mv cakephp-cakephp-* ./cakephp
  - chmod -R 777 ./cakephp/app/tmp
  - wget http://downloads.sourceforge.net/simpletest/simpletest_1.0.1.tar.gz -O simpletest.tar.gz
  - tar xf simpletest.tar.gz
  - mv simpletest/ ./cakephp/app/vendors/
  - cp -R ./CakePHP-ACL-Plugin ./cakephp/app/plugins/acl
  - echo "<?php
    require_once('acl.php');
    " > cakephp/app/config/bootstrap.php
  - mv cakephp/app/plugins/acl/config/acl.php cakephp/app/config/acl.php
  - echo "<?php
    class DATABASE_CONFIG {
      public $default = array();
      public $test = array();
      public function __construct() {
        $db = (!empty($_SERVER['DB'])) ? $_SERVER['DB'] : 'mysql';
        switch ($db) {
        case 'pgsql':
          $this->default = $this->test = array(
            'driver' => 'postgres',
            'persistent' => false,
            'host' => '127.0.0.1',
            'login' => 'postgres',
            'password' => '',
            'database' => 'cakephp_test',
            'prefix' => '',
            'encoding' => 'utf8'
          );
          break;
        case 'mysql':
        default:
          $this->default = $this->test = array(
            'driver' => 'mysql',
            'persistent' => false,
            'host' => '0.0.0.0',
            'login' => 'root',
            'password' => '',
            'database' => 'cakephp_test',
            'prefix' => ''
          );
        }
      }
    }
    " > cakephp/app/config/database.php
  - cd ./cakephp

script:
  - php cake/console/cake testsuite acl all
