language: php

php:
  - 5.2
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - cd ../
  - wget https://github.com/cakephp/cakephp/tarball/1.3.15 -O cake.tar.gz
  - tar xf cake.tar.gz
  - mv cakephp-cakephp-* ./cakephp
  - chmod -R 777 ./cakephp/app/tmp
  - wget http://downloads.sourceforge.net/simpletest/simpletest_1.0.1.tar.gz -O simpletest.tar.gz
  - tar xf simpletest.tar.gz
  - mv simpletest/ ./cakephp/app/vendors/
  - cp -R ./CakePHP-ACL-Plugin ./cakephp/app/plugins/acl
  - echo "<?php
    require_once('acl.php');
    " > cakephp/app/config/bootstrap.php
  - mv cakephp/app/plugins/acl/config/acl.php cakephp/app/config/acl.php
  - echo "<?php
    class DATABASE_CONFIG {
      private \$identities = array(
        'mysql' => array(
          'driver' => 'mysql',
          'host' => '0.0.0.0',
          'login' => 'travis'
        ),
        'pgsql' => array(
          'driver' => 'postgres',
          'host' => '127.0.0.1',
          'login' => 'postgres',
          'database' => 'cakephp_test',
          'schema' => array(
            'default' => 'public',
            'test' => 'public',
          )
        ),
        'sqlite' => array(
          'driver' => 'sqlite',
          'database' => array(
            'default' => ':memory:',
            'test' => ':memory:',
          ),
        )
      );
      var \$default = array(
        'persistent' => false,
        'host' => '',
        'login' => '',
        'password' => '',
        'database' => 'cakephp_test',
        'prefix' => ''
      );

      var \$test = array(
        'persistent' => false,
        'host' => '',
        'login' => '',
        'password' => '',
        'database' => 'cakephp_test',
        'prefix' => ''
      );

      public function __construct() {
        \$db = 'mysql';
        if (!empty(\$_SERVER['DB'])) {
          \$db = \$_SERVER['DB'];
        }
        foreach (array('default', 'test') as \$source) {
          \$config = array_merge(\$this->{\$source}, \$this->identities[\$db]);
          if (is_array(\$config['database'])) {
            \$config['database'] = \$config['database'][\$source];
          }
          if (!empty(\$config['schema']) && is_array(\$config['schema'])) {
            \$config['schema'] = \$config['schema'][\$source];
          }
          \$this->{\$source} = \$config;
        }
      }
    }" > cakephp/app/config/database.php
  - cd ./cakephp

script:
  - php cake/console/cake.php testsuite acl case models/admin_user
  - php cake/console/cake.php testsuite acl case models/admin_group
  - php cake/console/cake.php testsuite acl case components/acl_reflector
  - php cake/console/cake.php testsuite acl case components/acl_manager
  - php cake/console/cake.php testsuite acl all
